# 7절. 연습문제
## 실습형

In [1]:
#1)다음 코드는 iris 데이터의 독립변수(sepal_length, sepal_width, petal_length, petal_length)
#정보만 갖도록 한 코드입니다. 이를 이용해서 주어진 문제를 해결하세요.
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
print(iris_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
type(iris_data), iris_data.dtype, iris_data.shape # 150행 4열짜리 float64 배열

(numpy.ndarray, dtype('float64'), (150, 4))

In [5]:
#1-1) 각 변수별 평균을 출력하세요 (열별 평균)
# array([5.84333333, 3.05733333, 3.758, 1.19933333])
mean_values = np.mean(iris_data, axis=0)
print(mean_values)

[5.84333333 3.05733333 3.758      1.19933333]


In [6]:
#2) 처음 다섯개 행을 출력하세요
# array([[5.1, 3.5, 1.4, 0.2],
#        [4.9, 3., 1.4, 0.2],
#        [4.7, 3.2, 1.3, 0.2],
#        [4.6, 3.1, 1.5, 0.2],
#        [5., 3.6, 1.4, 0.2]])
print(iris_data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
#3) 처음 다섯개 행에서 마지막 열을 제외한 나머지 열을 출력하세요.
# array([[5.1, 3.5, 1.4],
#        [4.9, 3., 1.4],
#        [4.7, 3.2, 1.3],
#        [4.6, 3.1, 1.5],
#        [5., 3.6, 1.4]])
print(iris_data[:5, :-1])

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]


In [8]:
# 4.처음 다섯개 행에서 마지막 열만 출력하세요
# array([0.2, 0.2, 0.2, 0.2, 0.2])
print(iris_data[:5, -1])

[0.2 0.2 0.2 0.2 0.2]


In [9]:
# 5.3번 배열과 4번 배열을 원래 모양이 되도록 합치세요. 실행 결과는 2번의 결과와 같아야 합니다.
thplusfo = np.hstack((iris_data[:5, :-1], iris_data[:5, -1][:, np.newaxis]))
print(thplusfo)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
# 6.처음 다섯 개 행을 이용해서 각 열 별로 평균보다 큰 값들만 출력하세요
twoq = iris_data[:5]
oneq = np.mean(twoq, axis=0)
result = twoq > oneq

print(twoq[result])

[5.1 3.5 4.9 1.5 5.  3.6]


## 문제풀이형

In [ ]:
# 1) 3
# 2) 4
# 3) 1
# 4) 2
# 5) 2